name: Build, Install, Test, and Coverage

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    workflow_dispatch:

jobs:

  build_install_test_coverage:
      runs-on: ubuntu-latest

      strategy:
        fail-fast: false

      env:
        OSQP_BUILD_DIR_PREFIX: ${{ github.workspace }}/build
        OSQP_INSTALL_PREFIX: ${{ github.workspace }}/../install
        CTEST_OUTPUT_ON_FAILURE: 1

      steps:
        - uses: actions/checkout@v4
          with:
            lfs: false
            submodules: recursive
        - name: Set up conda environment for testing
          uses: conda-incubator/setup-miniconda@v3
          with:
              auto-update-conda: true
              python-version: 3.9
              activate-environment: osqp-test
              environment-file: tests/testenv.yml
              auto-activate-base: false

        - name: Setup (Linux)
          if: runner.os == 'Linux'
          run: |
                echo "LD_LIBRARY_PATH=$CONDA_PREFIX/lib" >> $GITHUB_ENV
                conda install -c conda-forge libstdcxx-ng
    
        - name: Install MKL
          run: |
                conda install -c https://software.repos.intel.com/python/conda/ mkl-devel
                conda info
                conda list

        - name: Install Python dependencies
          run: |
            pip install numpy scipy

        - name: Build
          run: |
            cmake -G "Unix Makefiles" -S . -B build -DCMAKE_INSTALL_PREFIX=$OSQP_INSTALL_PREFIX -DOSQP_VERSION=0.99 -DOSQP_BUILD_UNITTESTS=ON
            cmake --build build
            cmake --install build

        # Test the executables can link using the installed CMake
        - name: OSQP Link Test
          run: |
            cmake -G "Unix Makefiles" -S tests/CMakeInstallTests -B tests/build -DOSQP_INSTALL_PREFIX=$OSQP_INSTALL_PREFIX
            cmake --build tests/build
            ./tests/build/osqp_static
            ./tests/build/osqp_shared
